### ISSUE TITLE
Why is reload() called?

### ISSUE THREAD

**Issue by gmberton** [amaralibey/MixVPR#11]
There are multiple calls to the reload() method in [here](https://github.com/amaralibey/MixVPR/blob/main/dataloaders/GSVCitiesDataloader.py#L125).
What is the purpose of that method?

**Comment by amaralibey** [comment]
Hello @gmberton, sorry for the late answer,

The `reload()` method creates a new instance of the dataset object. It is initially called in the `setup()` method, which is required for Lightning datamodule. If the `reload_dataloaders_every_n_epochs` parameter is set to a value greater than 0 (in the Trainer), then the `train_dataloader()` method is called to re-instantiate the dataset after every `n` iterations.

Since both the `setup()` and `train_dataloader()` methods instantiate the dataset, it is more efficient to have a single `reload()` method that can be called in both cases.
